language: java
jdk:
  - openjdk8
  - openjdk13

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x ./card/gradlew

script:
  - cd card && ./gradlew clean build